PORTNAME=       ctv
PORTVERSION=    1.0.0
CATEGORIES=     textproc

MAINTAINER=     jt@obs-sec.com
COMMENT=        Command-line Text Viewer - a simple interactive text-based file browser
WWW=		https://github.com/q5sys/ctv

LICENSE=        MIT
LICENSE_FILE=   ${WRKSRC}/LICENSE

USES=		ncurses cmake compiler:c++17-lang
USE_GITHUB=	yes
GH_ACCOUNT=	q5sys
GH_PROJECT=	ctv
GH_TAGNAME=	1.0.0

PLIST_FILES=    bin/ctv

.include <bsd.port.mk>
